name: KannystraPluggins
version: '0.9'
main: kannysta.plugins.KannystraPluggins
api-version: '1.21'
commands:
  language:
    usage: /language
  мова:
    usage: /мова
  язык:
    usage: /язык
  hub:
    usage: /hub
    aliases:
      - хаб
  worlds:
    aliases:
      - світи
      - миры
  menu:
    aliases:
      - меню
  pvp:
    aliases:
      - pvpworlds
      - пвп
      - пвпсвіти
      - пвпмиры
  feed:
    aliases:
      - голод
      - годувати
      - кормить
  rtp:
    aliases:
      - randomtp
      - ртп
  netherPvp:
    aliases:
      - npvp
      - npot
      - netherpot
      - нпот
      - незерпвп
      - нпвп
  customize:
    aliases:
      - custom
      - settings
      - кастом
      - кастомизация
      - настройки
      - кастомізація
      - налаштування
  guichecker:
    aliases:
      - GuiChecker
      - GUICHECKER